upload-path: F:/qtms/resource/

server:
  port: 8080

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8
     username: root
     password: ktcatv
     driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:file:${upload-path}
  mvc:
    static-path-pattern: /static/**