upload-path: F:/blog/resource/
#database-path: 132.232.92.140:3306
database-path: 127.0.0.1:3306
database-username: root
database-password: ktcatv
blog-env: windows
port: 8080
log-path: F:/blog/log/


server:
  port: ${port}
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
     url: jdbc:mysql://${database-path}/blog?useUnicode=true&characterEncoding=utf-8
     username: ${database-username}
     password: ${database-password}
     driver-class-name: com.mysql.jdbc.Driver
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:file:${upload-path}
#  mvc:
#    static-path-pattern: /static/**
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


#日志路径
logging:
  path: ${log-path}
  file:
    max-size: 10Mb
  level:
    com.ktcatv.qtms.mapper: debug

pagehelper:
  reasonable: false
  support-methods-arguments: true
  helper-dialect: mysql
